version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=music-shop
    ports:
      - "5732:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
